FROM bitnami/minideb:stretch

ENV http_proxy http://clientproxy.corproot.net:8079/
ENV https_proxy http://clientproxy.corproot.net:8079/
ENV no_proxy corproot.net,swissptt.ch,swisscom.com,127.0.0.1,localhost

RUN apt-get update && apt-get install -y wget curl rake bundler nodejs git

# Golang
RUN wget -O /usr/local/go1.9.linux-amd64.tar.gz https://storage.googleapis.com/golang/go1.9.linux-amd64.tar.gz && \
    cd /usr/local/ && tar -xvzf go1.9.linux-amd64.tar.gz && \
    rm -rf go1.9.linux-amd64.tar.gz && \
    mkdir -p /usr/local/go_work

ENV GOROOT /usr/local/go
ENV GOPATH /usr/local/go
ENV PATH $GOROOT/bin:$GOPATH/bin:$PATH

# CloudFoundry Cli
RUN wget http://go-cli.s3-website-us-east-1.amazonaws.com/releases/v6.13.0/cf-linux-amd64.tgz && \
    tar -xvzf cf-linux-amd64.tgz && mv cf /sbin/ && chmod +x /sbin/cf && rm cf-linux-amd64.tgz